name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  meltano-run:
    name: "Meltano run with that ${{ matrix.overwrite_state && 'overwrites state' || 'does not overwrite state' }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        overwrite_state: ["true", "false"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pipx install 'meltano[s3]'
      - run: meltano install
      - name: Start MinIO
        run: >
          docker run -d
          -p 9000:9000
          -p 9001:9001
          -e MINIO_ROOT_USER=minio
          -e MINIO_ROOT_PASSWORD=minio-secret
          -v $PWD/s3/:/data
          --name minio minio/minio:latest
          server /data --console-address ":9001"

      - name: Sync all streams
        env:
          TAP_OVERWRITES_STATE__SELECT: '["*.*"]'
        run: |
          meltano run tap-overwrites-state target-jsonl
      - name: Inspect state
        run: |
          meltano state get dev:tap-overwrites-state-to-target-jsonl | jq

      - name: Sync a subset of streams
        env:
          TAP_OVERWRITES_STATE__SELECT: '["stream_1", "stream_2"]'
        run: |
          meltano run tap-overwrites-state target-jsonl
      - name: Inspect state
        run: |
          meltano state get dev:tap-overwrites-state-to-target-jsonl | jq
